### PR TITLE
fix: view lifecycle issue

### LINKED ISSUE #309: The specified child already has a parent. You must call removeView() on the child's parent first.
We're getting this error occasionally java.lang.IllegalStateException - The specified child already has a parent. You must call removeView() on the child's parent first. Nav sdk 0.6.1 on android only

```
 Fatal Exception: com.google.android.libraries.navigation.internal.mq.b: ab{property=ab{propertyType=ARROW_PAGER_ITEMS, layout=com.google.android.libraries.navigation.internal.tx.k, view=com.google.android.libraries.geo.navcore.ui.header.views.SwipeableHeaderView{bef9379 V.E...... ......ID 0,0-720,278 #7f0902fe app:id/step_cue_header viewInfo = }, propertyValue=[com.google.android.libraries.navigation.internal.ts.a@c86d8be, com.google.android.libraries.navigation.internal.ts.a@c685d1f, com.google.android.libraries.navigation.internal.ts.a@9c9486c, com.google.android.libraries.navigation.internal.ts.a@e4cee35, com.google.android.libraries.navigation.internal.ts.a@953c2ca]}, viewModel=com.google.android.libraries.navigation.internal.ts.d@357b6ac}
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5380)
       at android.view.ViewGroup.addView(ViewGroup.java:5201)
       at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
       at android.view.ViewGroup.addView(ViewGroup.java:5136)
       at android.view.ViewGroup.addView(ViewGroup.java:5108)
       at com.google.android.libraries.navigation.internal.mo.b.instantiateItem(PG:7)
       at com.google.android.apps.gmm.base.views.viewpager.j.instantiateItem(PG:1)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
       at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
       at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
       at com.google.android.apps.gmm.base.views.viewpager.j.c(PG:6)
       at com.google.android.apps.gmm.base.views.viewpager.i.onChanged(PG:2)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
       at com.google.android.libraries.navigation.internal.mo.b.b(PG:3)
       at com.google.android.apps.gmm.base.views.viewpager.g.a(PG:9)
       at com.google.android.libraries.navigation.internal.ms.a.g(PG:4)
       at com.google.android.libraries.navigation.internal.ms.c.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.bd.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:10)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.q(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.m(PG:1)
       at com.google.android.libraries.navigation.internal.mn.cs.a(PG:6)
       at com.google.android.libraries.navigation.internal.mn.aj.invoke(:2)
       at com.google.android.libraries.navigation.internal.mn.am.a(PG:2)
       at com.google.android.libraries.navigation.internal.vm.cs.run(PG:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at com.google.android.libraries.navigation.internal.if.b.run(PG:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        
```

```
          Caused by java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5380)
       at android.view.ViewGroup.addView(ViewGroup.java:5201)
       at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
       at android.view.ViewGroup.addView(ViewGroup.java:5136)
       at android.view.ViewGroup.addView(ViewGroup.java:5108)
       at com.google.android.libraries.navigation.internal.mo.b.instantiateItem(PG:7)
       at com.google.android.apps.gmm.base.views.viewpager.j.instantiateItem(PG:1)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
       at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
       at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:1086)
       at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:3097)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:291)
       at com.google.android.apps.gmm.base.views.viewpager.j.c(PG:6)
       at com.google.android.apps.gmm.base.views.viewpager.i.onChanged(PG:2)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:294)
       at com.google.android.libraries.navigation.internal.mo.b.b(PG:3)
       at com.google.android.apps.gmm.base.views.viewpager.g.a(PG:9)
       at com.google.android.libraries.navigation.internal.ms.a.g(PG:4)
       at com.google.android.libraries.navigation.internal.ms.c.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.bd.b(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:10)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.s(PG:13)
       at com.google.android.libraries.navigation.internal.mn.cc.r(PG:4)
       at com.google.android.libraries.navigation.internal.mn.cc.q(PG:3)
       at com.google.android.libraries.navigation.internal.mn.cc.m(PG:1)
       at com.google.android.libraries.navigation.internal.mn.cs.a(PG:6)
       at com.google.android.libraries.navigation.internal.mn.aj.invoke(:2)
       at com.google.android.libraries.navigation.internal.mn.am.a(PG:2)
       at com.google.android.libraries.navigation.internal.vm.cs.run(PG:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at com.google.android.libraries.navigation.internal.if.b.run(PG:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        
```

### PR DESCRIPTION
**Pull request by jokerttu**
- Improves how views are created by dropping createFragment command call
- Improves how views are disposed and fragments removed on Android platform
- Improves null checking for both platforms

Fixes #309

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation
- [ ] I added new tests to check the change I am making
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/googlemaps/react-native-navigation-sdk/blob/main/CONTRIBUTING.md
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: ios/react-native-navigation-sdk/NavModule.m [hunk 1]
```diff
@@ -411,8 +411,9 @@ - (void)showTermsAndConditionsDialog {
 }
 
 - (void)setDisplayOptionsToViews:(NSDictionary *)options {
-  for (NavViewController *viewController in [NavViewModule sharedInstance]
-           .viewControllers.allValues) {
+  NSEnumerator *enumerator = [[NavViewModule sharedInstance].viewControllers objectEnumerator];
```
Comment (illuminati1911) [inline ios/react-native-navigation-sdk/NavModule.m:414]: What was the reason to change to this from for loop?

**Review by illuminati1911 — APPROVED** [review]
Looks good to me!

**Comment by jokerttu** [comment]
Converted as draft, as this do not solve all issues just yet.
Fragment creation needs to be updated so that it won't crash if view is not drawn to view hierarchy.
